use_frameworks!
inhibit_all_warnings!

target 'Soundcloud iOS' do
    platform :ios, '8.0'

    pod 'KeychainAccess', '~> 4.1.0'
end

target 'Soundcloud OSX' do
    platform :osx, '10.10'

    pod 'KeychainAccess', '~> 4.1.0'
end

target 'SoundcloudTests' do
    platform :ios, '8.0'

    pod 'KeychainAccess', '~> 4.1.0'
end

target 'SoundcloudAppTest' do
    platform :ios, '8.0'

    pod 'KeychainAccess', '~> 4.1.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = '5.0'
      configuration.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

